name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install mkdocs-minify-plugin mkdocs-redirects mkdocs-mermaid2-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pymdown-extensions

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
